[DEFAULT]
user=ocid1.user.oc1..aaaaaaaara6d73iy3sho6dmpogkrbk5yss3g33q337sgditudnaeo3qth6aq
fingerprint=dd:14:a4:8d:c5:20:06:d6:8f:dc:8b:cd:61:e3:39:d4
tenancy=ocid1.tenancy.oc1..aaaaaaaayfuejyqsqyk36ctd5iaor2dbtsn5wbsijaknr22i2dwezlj5r2va
region=us-ashburn-1
key_file=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCxXoVTCar2rRIK
YFQdAELhCHd0na2Q3PJ9JmWDZ7VQkqGIcnwKcmH/8drZyJAD1K79fp0I9ZDFtha3
N5BMzpTpaYXGChEokBfvUSQcs/g31CrK9rAiT9oNqOO8cZKhGNOBjjnfB59sgtob
3xE/VPJP1CSSRu9KXRxx8fUBQJEA3PE8UjSorAz2Y/nlp+xTq9Zc+QN0Ut7r4z+1
i8lSaCyvhNCRWw+vSe+nFeLcA7xNA2oWF7pbhc37RR+Ko17f4k2Edjn6pOiMRZwW
Jd+CcHljQfrGyfwrG7d+Z7Wpsrn38b8+e6+LHKCBpQLRgUnohTfJHFn2DbmkG4x7
VhBqd+JPAgMBAAECggEAVjYBqsNbuGuWBbodmD0MxNF3MpUDjJKAQMlddRn+/MtQ
vYAb/33qWVvGiq2cJmiFp8wXawflFtxzPRnCRzrwEWXLcl9pSKSFJbr0SQlG4Gf9
ZsqyAPN8IsCQ9QLlCO2GvIWTZm8Pk9AkUIDDottYremI3xqga65HSbEX68Rk1pw8
pieLY8F5Aw29xavnxbhGGMD5DY8nFL+k2mHbfCUV2EMOS6/V02yLkOLx4X0gv2WF
HRqLgC+9C4ag/HkkM3UqRByG8GFKX688CuU/PybxX0iUKyZ4S5cC5UN2E7ZqdVnT
QDTDWAmBE5pey0SYg2rxHptUWg/MXKEB861A2/1CvQKBgQDzLHQBa7Fil8jKLiek
aNyqOg0Lj7lKVS8OIdtKgFku0zAwW/nOTiZCcl76PjDKerODSg08GlsclJuCwRug
P4wxCh0zvNylZ1C5lhV+242dPzDs3cAp6AWE19znlOXLoGNJjVlJC3olAZWehFOM
hErQ98ILnXhCmClNNhpBZcHNHQKBgQC6uYSOYuBnabPfPVUKb8ofd3INMY1bEFz+
Ctl8oWzEH5TF5Ng8fLSq/QZyu6fToMff/jxnPXS7VQJGhrSUP7O6I/0eOy01DW/Q
W1GOiIfXhaaVJbqti/CDvr3LS5HRHnd1VYSHuSZArg/MaOTA8pRqI/gD9OfJtxLL
Y9v27xeNWwKBgBJv92e4K53nFkFGGJldngWGG0EaJ5lcNhIjPQY8Dwb+2jOAdcNP
p5T4KP1eQ8LGZN/6eGBrOydCmTvjul1/E/kP5EDs++nKmJNJrt2MdgNLLEF5Wr2S
qwB0gXpJjtbOlViZUAC6zwsJQLfhHpiT2zxW3K6WxOx/rvn8tSbqOTR9AoGAcGVl
djPscjM9U55ehza9Su2iWHDAbtVNtJmhSpT8nJ2J9wkGZHqIYfiGnh95KTk5twoZ
H+ftUSodgYhqQGaL7/rjzQO/9ZRN/vRJBmwGoOPRXyvjz71RnGv/YNTvRBp7u8Qr
T2tSrFJaLifhsocScUWPcApGT7SEeqt0Z5KJ8csCgYBAj4MBuL9Eoc4a/e9B+Pi/
xQofLi3JrS36WzqdsSE0PPNkvH6LyNYKIhst0pehMWycnV8egyLVIG2ygtoXSEyJ
1tmEwPV5119GIsdl2k8rrL60HOx+qWACrY7pDGLnN00De3VyB4eeckccc739AeJT
IlG0sPIzUJrEUh5wdAzHP
 # TODO
